export const GAME_START_LOADING = 'GAME_START_LOADING';
export const GAME_FINISH_LOADING = 'GAME_FINISH_LOADING';
export const GAME_LOADING_ERROR = 'GAME_LOADING_ERROR';
export const ARCADE_START_LOADING = 'ARCADE_START_LOADING';
export const ARCADE_FINISH_LOADING = 'ARCADE_FINISH_LOADING';
export const ARCADE_LOADING_ERROR = 'ARCADE_LOADING_ERROR';